#
# Makefile for USB Class drivers
# (one step up from the misc category)
#

obj-$(CONFIG_USB_ACM)		+= cdc-acm.o
obj-$(CONFIG_USB_PRINTER)	+= usblp.o
obj-$(CONFIG_USB_WDM)		+= cdc-wdm.o
obj-$(CONFIG_USB_WDM_SYNO)		+= cdc-wdm_syno.o
obj-$(CONFIG_USB_TMC)		+= usbtmc.o
