
/*
	REGISTER OFFSET_ADDRESS R/W DESCRIPTION RESET VALUE
*/

#define	C2K_RTC_RTCCON 0X00 /* R/W RTC CONTROL REGISTER 0X00 */
#define	C2K_RTC_RTCALM 0X04 /* R/W RTC ALARM CONTROL REGISTER 0X00 */
#define	C2K_RTC_ALMSEC 0X08 /* R/W ALARM SECOND DATA REGISTER 0X00 */
#define	C2K_RTC_ALMMIN 0X0C /* R/W ALARM MINUTE DATA REGISTER 0X00 */
#define	C2K_RTC_ALMHOUR 0X10 /* R/W ALARM HOUR DATA REGISTER 0X00 */
#define	C2K_RTC_ALMDATE 0X14 /* R/W ALARM DATE DATA REGISTER 0X00 */
#define	C2K_RTC_ALMDAY 0X18 /* R/W ALARM DAY OF WEEK DATA REGISTER 0X00 */
#define	C2K_RTC_ALMMON 0X1C /* R/W ALARM MONTH DATA REGISTER 0X00 */
#define	C2K_RTC_ALMYEAR 0X20 /* R/W ALARM YEAR DATA REGISTER 0X00 */
#define	C2K_RTC_BCDSEC 0X24 /* R/W BCD SECOND REGISTER */
#define	C2K_RTC_BCDMIN 0X28 /* R/W BCD MINUTE REGISTER */
#define	C2K_RTC_BCDHOUR 0X2C /* R/W BCD HOUR REGISTER */
#define	C2K_RTC_BCDDATE 0X30 /* R/W BCD DATE REGISTER */
#define	C2K_RTC_BCDDAY 0X34 /* R/W BCD DAY OF WEEK REGISTER */
#define	C2K_RTC_BCDMON 0X38 /* R/W BCD MONTH REGISTER */
#define	C2K_RTC_BCDYEAR 0X3C /* R/W BCD YEAR REGISTER */
#define	C2K_RTC_RTCIM 0X40 /* R/W RTC INTERRUPT MODE REGISTER 0X00 */
#define	C2K_RTC_RTCPEND 0X44 /* R/W RTC INTERRUPT PENDING REGISTER 0X00 */

